create table tb_role (id int4 generated by default as identity, role_name varchar(255), primary key (id));
create table tb_user (id int4 generated by default as identity, email varchar(255), name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (user_id int4 not null, role_id int4 not null, primary key (user_id, role_id));
alter table if exists tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table if exists tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
